version: "3.3"
services:
  ubuntu:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: /d/sync/
        target: /host/
    container_name: focal
    restart: always
    tty: true
    environment:
      LANG: "C.UTF-8"

# WARNING: apt does not have a stable CLI interface. Use with caution in scripts.    
# replace apt install xxx with apt-get install xxx

# when build successful, exec: docker exec -it linuxos zsh